language: php

php:
  - 5.3
  - 5.4

services:
  - mysql

env:
  - DB=mysql

before_install:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mwi_tests;" -uroot; fi
  - cd ~/builds
  - git clone git://github.com/Myopengrid/mwi.git
  - git clone git://github.com/Myopengrid/thumbnails.git
  - mv ./thumbnails ./mwi/bundles/thumbnails
  - git clone git://github.com/JeffCost/travis.git
  - mv ./travis ./mwi/bundles/travis
  - mv ./mwi/bundles/travis/tests ./mwi/application/config
  - mv ./mwi/bundles/travis/paths.php ./mwi/paths.php
  - mv ./mwi/bundles/travis/application.php ./mwi/application/config/application.php
  - echo "<?php return array('travis' => array('auto' => true));" > ./mwi/application/bundles.php
  - cd ./mwi

script: 
  - php artisan travis::test:installapp
  - php artisan test thumbnails
